name: Release
on:
  push:
    tags:
      - 'v*'
jobs:

  release:
    name: Prepare release

    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]

    steps:
      - uses: actions/checkout@v1
      - name: Run linters and tests based on "docker build" approach
        run: docker build -f Dockerfile.test .
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - run: RELEASE=${RELEASE} GOOS=${GOOS} GOARCH=${GOARCH} make build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          RELEASE: $(basename ${{ github.ref }})
      - uses: actions/upload-artifact@v1
        with:
          name: tr-$(basename ${{ github.ref }})-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./bin/${{ matrix.goos }}-${{ matrix.goarch }}/tr
